/**
 * Datos de ejemplo del taller (Excel «Datos_demo_Catálogo_Indicadores_Desempeño»): indicadores por programa
 * presupuestal. Alimentan las sugerencias de autocompletado del formulario DETALLE, acotadas al programa elegido.
 * Cada campo se sigue completando y seleccionando a mano; estas listas solo ofrecen las opciones del PP.
 */
export interface IndicadorDemo {
  codigo: string;
  pp: string;
  nombre: string;
  dimension: string;
  nivelMedicion: string;
  productoCodigo: string;
  alcance: string;
  nivelResponsable: string;
  unidad: string;
  tipoCalculo: string;
  numerador: string;
  denominador: string;
  formula: string;
  sentido: string;
  tipoFuente: string;
  fuenteDatos: string;
  limitacion: string;
  supuestos: string;
  precisiones: string;
  periodicidad: string;
  programacion: string;
  gestion: string;
  evaluacion: string;
  anioInicio: string;
  anioFin: string;
  estado: string;
  fechaDesde: string;
  fechaHasta: string;
  desagregaciones: { ambito: string; area: string; periodicidad: string }[];
  variables: { variable: string; descripcion: string; fuente: string; tipoVariable: string }[];
  validaciones: { elemento: string; descripcion: string }[];
}

export const INDICADORES_DEMO: IndicadorDemo[] = [
  {
    codigo: "9001",
    pp: "1006",
    nombre: "Tasa de victimización por delitos patrimoniales en zonas urbanas",
    dimension: "eficacia",
    nivelMedicion: "1. Resultado específico",
    productoCodigo: "",
    alcance: "Nacional y Regional",
    nivelResponsable: "Nacional",
    unidad: "Tasa",
    tipoCalculo: "numerador",
    numerador: "Personas de 15 años a más víctimas de delitos patrimoniales",
    denominador: "Población de 15 años a más",
    formula: "",
    sentido: "Bajar",
    tipoFuente: "Encuesta",
    fuenteDatos: "Encuesta Nacional de Programas Presupuestales (ENAPRES) – INEI",
    limitacion: "Inferencia solo a nivel departamental urbano",
    supuestos: "Se mantiene el diseño muestral de la encuesta",
    precisiones: "Periodo de referencia: últimos 12 meses",
    periodicidad: "Semestral",
    programacion: "SI",
    gestion: "SI",
    evaluacion: "SI",
    anioInicio: "2026",
    anioFin: "",
    estado: "SI",
    fechaDesde: "23/01/2026",
    fechaHasta: "",
    desagregaciones: [{ ambito: "4 AREQUIPA", area: "2 URBANO", periodicidad: "Semestral" }, { ambito: "13 LA LIBERTAD", area: "2 URBANO", periodicidad: "Semestral" }, { ambito: "15 LIMA", area: "2 URBANO", periodicidad: "Trimestral" }, { ambito: "20 PIURA", area: "2 URBANO", periodicidad: "Semestral" }],
    variables: [{ variable: "victimas_delito_patrimonial", descripcion: "Personas de 15 años a más que declaran haber sido víctimas de algún delito patrimonial en los últimos 12 meses", fuente: "ENAPRES – INEI, módulo de seguridad ciudadana", tipoVariable: "Categórica dicotómica (1 = sí, 0 = no)" }, { variable: "poblacion_15_mas_urbana", descripcion: "Población de 15 años a más residente en zonas urbanas", fuente: "ENAPRES – INEI, módulo de seguridad ciudadana", tipoVariable: "Numérica discreta (conteo)" }, { variable: "factor_expansion", descripcion: "Factor de expansión anual de la persona, para obtener estimaciones poblacionales", fuente: "ENAPRES – INEI, módulo de seguridad ciudadana", tipoVariable: "Numérica continua (ponderador)" }],
    validaciones: [{ elemento: "Filtro de área de residencia", descripcion: "Se consideran solo los registros con área de residencia urbana" }, { elemento: "Ponderación con factor de expansión", descripcion: "Las estimaciones se calculan aplicando el factor de expansión anual de la encuesta" }, { elemento: "Exclusión de respuestas faltantes", descripcion: "Se excluyen los registros sin respuesta en la pregunta de victimización" }],
  },
  {
    codigo: "9002",
    pp: "1006",
    nombre: "Porcentaje de población que confía en la Policía Nacional",
    dimension: "calidad",
    nivelMedicion: "1. Resultado específico",
    productoCodigo: "",
    alcance: "Nacional",
    nivelResponsable: "Nacional",
    unidad: "Porcentaje",
    tipoCalculo: "numerador",
    numerador: "Personas que declaran confiar en la PNP",
    denominador: "Total de personas entrevistadas",
    formula: "",
    sentido: "Subir",
    tipoFuente: "Encuesta",
    fuenteDatos: "Encuesta Nacional de Programas Presupuestales (ENAPRES) – INEI",
    limitacion: "Percepción sujeta a coyuntura",
    supuestos: "Se mantiene la pregunta en el cuestionario",
    precisiones: "Confianza: respuestas «mucha» o «suficiente»",
    periodicidad: "Anual",
    programacion: "SI",
    gestion: "NO",
    evaluacion: "NO",
    anioInicio: "2027",
    anioFin: "",
    estado: "SI",
    fechaDesde: "02/03/2026",
    fechaHasta: "",
    desagregaciones: [],
    variables: [{ variable: "confia_policia_nacional", descripcion: "Persona que declara tener mucha o suficiente confianza en la Policía Nacional del Perú", fuente: "ENAPRES – INEI, módulo de seguridad ciudadana", tipoVariable: "Categórica dicotómica (1 = sí, 0 = no)" }, { variable: "total_personas_entrevistadas", descripcion: "Total de personas de 15 años a más entrevistadas en el módulo", fuente: "ENAPRES – INEI, módulo de seguridad ciudadana", tipoVariable: "Numérica discreta (conteo)" }, { variable: "factor_expansion", descripcion: "Factor de expansión anual de la persona, para obtener estimaciones poblacionales", fuente: "ENAPRES – INEI, módulo de seguridad ciudadana", tipoVariable: "Numérica continua (ponderador)" }],
    validaciones: [{ elemento: "Recodificación de la confianza", descripcion: "Las respuestas «mucha» y «suficiente» se recodifican como 1; las demás como 0" }, { elemento: "Ponderación con factor de expansión", descripcion: "Las estimaciones se calculan aplicando el factor de expansión anual de la encuesta" }, { elemento: "Control de rango del resultado", descripcion: "El valor calculado debe estar entre 0 y 100; si no, se revisan numerador y denominador" }],
  },
  {
    codigo: "9003",
    pp: "1006",
    nombre: "Porcentaje de ejecución presupuestal del programa respecto del PIM",
    dimension: "economia",
    nivelMedicion: "1. Resultado específico",
    productoCodigo: "",
    alcance: "Nacional",
    nivelResponsable: "Nacional",
    unidad: "Porcentaje",
    tipoCalculo: "numerador",
    numerador: "Monto devengado del PP",
    denominador: "PIM del PP",
    formula: "",
    sentido: "Subir",
    tipoFuente: "Registro administrativo",
    fuenteDatos: "SIAF-RP (PIM y devengado)",
    limitacion: "No refleja la calidad del gasto",
    supuestos: "El PIM se actualiza oportunamente",
    precisiones: "Corte al 31 de diciembre",
    periodicidad: "Semestral",
    programacion: "SI",
    gestion: "SI",
    evaluacion: "NO",
    anioInicio: "2026",
    anioFin: "",
    estado: "SI",
    fechaDesde: "23/01/2026",
    fechaHasta: "",
    desagregaciones: [],
    variables: [{ variable: "monto_devengado_programa", descripcion: "Monto devengado del programa presupuestal al cierre del año fiscal", fuente: "SIAF-RP, consulta de ejecución presupuestal", tipoVariable: "Numérica continua (soles)" }, { variable: "pim_del_programa", descripcion: "Presupuesto institucional modificado del programa presupuestal al cierre del año fiscal", fuente: "SIAF-RP, consulta de ejecución presupuestal", tipoVariable: "Numérica continua (soles)" }],
    validaciones: [{ elemento: "Corte de la información al cierre", descripcion: "Se usa la información al 31 de diciembre del año de medición" }, { elemento: "Control de denominador en cero", descripcion: "Si el denominador es cero, el indicador no se calcula y se reporta sin dato" }, { elemento: "Control de rango del resultado", descripcion: "El valor calculado debe estar entre 0 y 100; si no, se revisan numerador y denominador" }],
  },
  {
    codigo: "9004",
    pp: "1007",
    nombre: "Tasa de acciones terroristas por cada 100 000 habitantes en el ámbito de intervención",
    dimension: "eficacia",
    nivelMedicion: "1. Resultado específico",
    productoCodigo: "",
    alcance: "Nacional",
    nivelResponsable: "Nacional",
    unidad: "Tasa",
    tipoCalculo: "numerador",
    numerador: "N° de acciones terroristas registradas",
    denominador: "Población del ámbito de intervención",
    formula: "",
    sentido: "Bajar",
    tipoFuente: "Registro administrativo",
    fuenteDatos: "Registros policiales – Dirección contra el Terrorismo",
    limitacion: "Subregistro en zonas de difícil acceso",
    supuestos: "Continuidad del registro policial",
    precisiones: "Ámbito de intervención definido en el diseño del PP",
    periodicidad: "Anual",
    programacion: "SI",
    gestion: "SI",
    evaluacion: "NO",
    anioInicio: "2026",
    anioFin: "",
    estado: "SI",
    fechaDesde: "10/02/2026",
    fechaHasta: "",
    desagregaciones: [],
    variables: [{ variable: "acciones_terroristas_registradas", descripcion: "Acciones terroristas registradas en el ámbito de intervención durante el año", fuente: "Registros policiales – Dirección contra el Terrorismo", tipoVariable: "Numérica discreta (conteo)" }, { variable: "poblacion_ambito_intervencion", descripcion: "Población proyectada de los distritos del ámbito de intervención", fuente: "INEI, proyecciones de población distrital", tipoVariable: "Numérica discreta (conteo)" }],
    validaciones: [{ elemento: "Delimitación del ámbito de intervención", descripcion: "Solo se consideran los distritos del ámbito definido en el diseño del PP" }, { elemento: "Unicidad del evento registrado", descripcion: "Cada acción se cuenta una sola vez aunque tenga más de un reporte policial" }, { elemento: "Control de denominador en cero", descripcion: "Si el denominador es cero, el indicador no se calcula y se reporta sin dato" }],
  },
  {
    codigo: "9005",
    pp: "1008",
    nombre: "Porcentaje de residuos sólidos municipales dispuestos adecuadamente",
    dimension: "eficacia",
    nivelMedicion: "1. Resultado específico",
    productoCodigo: "",
    alcance: "Nacional, Regional y Local",
    nivelResponsable: "Local",
    unidad: "Porcentaje",
    tipoCalculo: "numerador",
    numerador: "Toneladas dispuestas en infraestructura autorizada",
    denominador: "Toneladas generadas",
    formula: "",
    sentido: "Subir",
    tipoFuente: "Registro administrativo",
    fuenteDatos: "SIGERSOL – MINAM",
    limitacion: "Reporte municipal incompleto",
    supuestos: "Las municipalidades reportan anualmente",
    precisiones: "Disposición en rellenos sanitarios autorizados",
    periodicidad: "Anual",
    programacion: "SI",
    gestion: "SI",
    evaluacion: "SI",
    anioInicio: "2026",
    anioFin: "",
    estado: "SI",
    fechaDesde: "23/01/2026",
    fechaHasta: "",
    desagregaciones: [{ ambito: "14 LAMBAYEQUE", area: "1 TOTAL", periodicidad: "Anual" }, { ambito: "13 LA LIBERTAD", area: "1 TOTAL", periodicidad: "Anual" }, { ambito: "22 SAN MARTIN", area: "1 TOTAL", periodicidad: "Anual" }],
    variables: [{ variable: "toneladas_dispuestas_autorizadas", descripcion: "Toneladas de residuos sólidos municipales dispuestas en infraestructura autorizada", fuente: "SIGERSOL – MINAM, reporte anual municipal", tipoVariable: "Numérica continua (toneladas)" }, { variable: "toneladas_generadas_municipales", descripcion: "Toneladas de residuos sólidos municipales generadas en el año", fuente: "SIGERSOL – MINAM, reporte anual municipal", tipoVariable: "Numérica continua (toneladas)" }],
    validaciones: [{ elemento: "Infraestructura con autorización vigente", descripcion: "Solo se cuentan las toneladas dispuestas en rellenos con autorización vigente" }, { elemento: "Control de denominador en cero", descripcion: "Si el denominador es cero, el indicador no se calcula y se reporta sin dato" }, { elemento: "Control de rango del resultado", descripcion: "El valor calculado debe estar entre 0 y 100; si no, se revisan numerador y denominador" }],
  },
  {
    codigo: "9006",
    pp: "1008",
    nombre: "Porcentaje de recaudación de arbitrios de limpieza pública respecto de lo emitido",
    dimension: "economia",
    nivelMedicion: "1. Resultado específico",
    productoCodigo: "",
    alcance: "Nacional, Regional y Local",
    nivelResponsable: "Local",
    unidad: "Porcentaje",
    tipoCalculo: "numerador",
    numerador: "Monto recaudado por arbitrios de limpieza pública",
    denominador: "Monto emitido",
    formula: "",
    sentido: "Subir",
    tipoFuente: "Registro administrativo",
    fuenteDatos: "Reportes municipales de recaudación",
    limitacion: "Información municipal heterogénea",
    supuestos: "Se mantiene la base de contribuyentes",
    precisiones: "Ejercicio fiscal vigente",
    periodicidad: "Anual",
    programacion: "SI",
    gestion: "NO",
    evaluacion: "NO",
    anioInicio: "2027",
    anioFin: "",
    estado: "SI",
    fechaDesde: "06/05/2026",
    fechaHasta: "",
    desagregaciones: [],
    variables: [{ variable: "monto_recaudado_arbitrios", descripcion: "Monto recaudado por arbitrios de limpieza pública en el ejercicio fiscal", fuente: "Reportes municipales de recaudación", tipoVariable: "Numérica continua (soles)" }, { variable: "monto_emitido_arbitrios", descripcion: "Monto emitido por arbitrios de limpieza pública en el ejercicio fiscal", fuente: "Reportes municipales de recaudación", tipoVariable: "Numérica continua (soles)" }],
    validaciones: [{ elemento: "Ejercicio fiscal de la recaudación", descripcion: "Recaudación y emisión corresponden al mismo ejercicio fiscal" }, { elemento: "Control de denominador en cero", descripcion: "Si el denominador es cero, el indicador no se calcula y se reporta sin dato" }, { elemento: "Control de rango del resultado", descripcion: "El valor calculado debe estar entre 0 y 100; si no, se revisan numerador y denominador" }],
  },
  {
    codigo: "9007",
    pp: "1009",
    nombre: "Porcentaje de hectáreas de cultivo ilícito reducidas respecto de lo programado",
    dimension: "eficacia",
    nivelMedicion: "1. Resultado específico",
    productoCodigo: "",
    alcance: "Nacional",
    nivelResponsable: "Nacional",
    unidad: "Porcentaje",
    tipoCalculo: "numerador",
    numerador: "Hectáreas reducidas",
    denominador: "Hectáreas programadas para reducción",
    formula: "",
    sentido: "Subir",
    tipoFuente: "Registro administrativo",
    fuenteDatos: "Reportes de reducción de cultivos – entidad responsable",
    limitacion: "Verificación de campo posterior",
    supuestos: "Condiciones de seguridad para las intervenciones",
    precisiones: "Hectáreas verificadas al cierre del año",
    periodicidad: "Anual",
    programacion: "SI",
    gestion: "SI",
    evaluacion: "NO",
    anioInicio: "2026",
    anioFin: "",
    estado: "SI",
    fechaDesde: "20/02/2026",
    fechaHasta: "",
    desagregaciones: [{ ambito: "10 HUANUCO", area: "3 RURAL", periodicidad: "Anual" }, { ambito: "22 SAN MARTIN", area: "3 RURAL", periodicidad: "Anual" }, { ambito: "25 UCAYALI", area: "3 RURAL", periodicidad: "Anual" }],
    variables: [{ variable: "hectareas_reducidas_verificadas", descripcion: "Hectáreas de cultivo ilícito reducidas y verificadas en campo", fuente: "Reportes de reducción de cultivos – entidad responsable", tipoVariable: "Numérica continua (hectáreas)" }, { variable: "hectareas_programadas_reduccion", descripcion: "Hectáreas programadas para reducción en el año", fuente: "Plan operativo anual – entidad responsable", tipoVariable: "Numérica continua (hectáreas)" }],
    validaciones: [{ elemento: "Verificación de campo de la reducción", descripcion: "Solo se cuentan las hectáreas con acta de verificación" }, { elemento: "Resultado mayor a 100", descripcion: "Si se reduce más de lo programado, el valor se reporta con una nota explicativa" }],
  },
  {
    codigo: "9008",
    pp: "0002",
    nombre: "Porcentaje de partos atendidos por personal calificado",
    dimension: "eficacia",
    nivelMedicion: "2. Producto",
    productoCodigo: "3033255",
    alcance: "Nacional y Regional",
    nivelResponsable: "Regional",
    unidad: "Porcentaje",
    tipoCalculo: "numerador",
    numerador: "Partos atendidos por personal calificado",
    denominador: "Total de partos",
    formula: "",
    sentido: "Subir",
    tipoFuente: "Encuesta",
    fuenteDatos: "Encuesta Demográfica y de Salud Familiar (ENDES) – INEI",
    limitacion: "Inferencia departamental",
    supuestos: "Se mantiene el módulo de la encuesta",
    precisiones: "Últimos 5 años previos a la encuesta",
    periodicidad: "Anual",
    programacion: "SI",
    gestion: "SI",
    evaluacion: "SI",
    anioInicio: "2026",
    anioFin: "",
    estado: "SI",
    fechaDesde: "23/01/2026",
    fechaHasta: "",
    desagregaciones: [{ ambito: "5 AYACUCHO", area: "2 URBANO", periodicidad: "Anual" }, { ambito: "5 AYACUCHO", area: "3 RURAL", periodicidad: "Anual" }, { ambito: "21 PUNO", area: "2 URBANO", periodicidad: "Anual" }, { ambito: "21 PUNO", area: "3 RURAL", periodicidad: "Anual" }],
    variables: [{ variable: "parto_personal_calificado", descripcion: "Parto atendido por médico, obstetra o enfermera", fuente: "ENDES – INEI, base de datos anual", tipoVariable: "Categórica dicotómica (1 = sí, 0 = no)" }, { variable: "total_partos_cinco_anios", descripcion: "Partos ocurridos en los cinco años previos a la entrevista", fuente: "ENDES – INEI, base de datos anual", tipoVariable: "Numérica discreta (conteo)" }, { variable: "factor_expansion", descripcion: "Factor de expansión anual de la persona, para obtener estimaciones poblacionales", fuente: "ENDES – INEI, base de datos anual", tipoVariable: "Numérica continua (ponderador)" }],
    validaciones: [{ elemento: "Periodo de referencia de los partos", descripcion: "Se consideran los partos de los cinco años previos a la entrevista" }, { elemento: "Ponderación con factor de expansión", descripcion: "Las estimaciones se calculan aplicando el factor de expansión anual de la encuesta" }, { elemento: "Control de rango del resultado", descripcion: "El valor calculado debe estar entre 0 y 100; si no, se revisan numerador y denominador" }],
  },
  {
    codigo: "9009",
    pp: "0002",
    nombre: "Ratio de gasto devengado por parto normal atendido",
    dimension: "eficiencia",
    nivelMedicion: "2. Producto",
    productoCodigo: "3033255",
    alcance: "Nacional",
    nivelResponsable: "Nacional",
    unidad: "Ratio",
    tipoCalculo: "otro",
    numerador: "",
    denominador: "",
    formula: "Monto devengado del producto / N° de partos normales atendidos",
    sentido: "Bajar",
    tipoFuente: "Registro administrativo",
    fuenteDatos: "SIAF-RP (devengado) y registro de atenciones",
    limitacion: "No incluye costos de otras fuentes de financiamiento",
    supuestos: "El registro de atenciones es completo",
    precisiones: "Soles por parto atendido",
    periodicidad: "Anual",
    programacion: "SI",
    gestion: "NO",
    evaluacion: "NO",
    anioInicio: "2027",
    anioFin: "",
    estado: "SI",
    fechaDesde: "15/04/2026",
    fechaHasta: "",
    desagregaciones: [],
    variables: [{ variable: "monto_devengado_producto", descripcion: "Monto devengado del producto 3033255 en el año fiscal", fuente: "SIAF-RP, consulta de ejecución presupuestal", tipoVariable: "Numérica continua (soles)" }, { variable: "partos_normales_atendidos", descripcion: "Partos normales atendidos en establecimientos del ámbito del programa", fuente: "Registro de atenciones del establecimiento", tipoVariable: "Numérica discreta (conteo)" }],
    validaciones: [{ elemento: "Correspondencia del periodo de medición", descripcion: "Devengado y atenciones corresponden al mismo año fiscal" }, { elemento: "Control de denominador en cero", descripcion: "Si el denominador es cero, el indicador no se calcula y se reporta sin dato" }],
  },
  {
    codigo: "9010",
    pp: "0002",
    nombre: "Porcentaje de gestantes con primera atención prenatal en el primer trimestre",
    dimension: "calidad",
    nivelMedicion: "2. Producto",
    productoCodigo: "3033261",
    alcance: "Nacional y Regional",
    nivelResponsable: "Regional",
    unidad: "Porcentaje",
    tipoCalculo: "numerador",
    numerador: "Gestantes con primera atención prenatal en el primer trimestre",
    denominador: "Total de gestantes atendidas",
    formula: "",
    sentido: "Subir",
    tipoFuente: "Encuesta",
    fuenteDatos: "Encuesta Demográfica y de Salud Familiar (ENDES) – INEI",
    limitacion: "Inferencia departamental",
    supuestos: "Se mantiene el módulo de la encuesta",
    precisiones: "Mide la oportunidad de la atención",
    periodicidad: "Anual",
    programacion: "SI",
    gestion: "SI",
    evaluacion: "NO",
    anioInicio: "2026",
    anioFin: "",
    estado: "SI",
    fechaDesde: "23/01/2026",
    fechaHasta: "",
    desagregaciones: [{ ambito: "6 CAJAMARCA", area: "1 TOTAL", periodicidad: "Anual" }, { ambito: "16 LORETO", area: "1 TOTAL", periodicidad: "Semestral" }, { ambito: "9 HUANCAVELICA", area: "1 TOTAL", periodicidad: "Anual" }],
    variables: [{ variable: "apn_primer_trimestre", descripcion: "Gestante con primera atención prenatal en el primer trimestre de gestación", fuente: "ENDES – INEI, base de datos anual", tipoVariable: "Categórica dicotómica (1 = sí, 0 = no)" }, { variable: "gestantes_con_atencion_prenatal", descripcion: "Gestantes con al menos una atención prenatal", fuente: "ENDES – INEI, base de datos anual", tipoVariable: "Numérica discreta (conteo)" }, { variable: "factor_expansion", descripcion: "Factor de expansión anual de la persona, para obtener estimaciones poblacionales", fuente: "ENDES – INEI, base de datos anual", tipoVariable: "Numérica continua (ponderador)" }],
    validaciones: [{ elemento: "Definición del primer trimestre", descripcion: "Primera atención dentro de las primeras 12 semanas de gestación" }, { elemento: "Ponderación con factor de expansión", descripcion: "Las estimaciones se calculan aplicando el factor de expansión anual de la encuesta" }, { elemento: "Control de rango del resultado", descripcion: "El valor calculado debe estar entre 0 y 100; si no, se revisan numerador y denominador" }],
  },
  {
    codigo: "9011",
    pp: "0002",
    nombre: "Porcentaje de ejecución presupuestal del producto de suplementación a gestantes",
    dimension: "economia",
    nivelMedicion: "2. Producto",
    productoCodigo: "3033263",
    alcance: "Nacional",
    nivelResponsable: "Nacional",
    unidad: "Porcentaje",
    tipoCalculo: "numerador",
    numerador: "Monto devengado del producto",
    denominador: "PIM del producto",
    formula: "",
    sentido: "Subir",
    tipoFuente: "Registro administrativo",
    fuenteDatos: "SIAF-RP (PIM y devengado)",
    limitacion: "No refleja la calidad del gasto",
    supuestos: "El PIM se actualiza oportunamente",
    precisiones: "Corte al 31 de diciembre",
    periodicidad: "Semestral",
    programacion: "SI",
    gestion: "SI",
    evaluacion: "NO",
    anioInicio: "2026",
    anioFin: "",
    estado: "SI",
    fechaDesde: "23/01/2026",
    fechaHasta: "",
    desagregaciones: [],
    variables: [{ variable: "monto_devengado_producto", descripcion: "Monto devengado del producto 3033263 en el año fiscal", fuente: "SIAF-RP, consulta de ejecución presupuestal", tipoVariable: "Numérica continua (soles)" }, { variable: "pim_del_producto", descripcion: "Presupuesto institucional modificado del producto 3033263", fuente: "SIAF-RP, consulta de ejecución presupuestal", tipoVariable: "Numérica continua (soles)" }],
    validaciones: [{ elemento: "Corte de la información al cierre", descripcion: "Se usa la información al 31 de diciembre del año de medición" }, { elemento: "Control de denominador en cero", descripcion: "Si el denominador es cero, el indicador no se calcula y se reporta sin dato" }, { elemento: "Control de rango del resultado", descripcion: "El valor calculado debe estar entre 0 y 100; si no, se revisan numerador y denominador" }],
  },
  {
    codigo: "9012",
    pp: "0002",
    nombre: "Porcentaje de mujeres en edad fértil que usan métodos modernos de planificación familiar",
    dimension: "eficacia",
    nivelMedicion: "2. Producto",
    productoCodigo: "3033262",
    alcance: "Nacional y Regional",
    nivelResponsable: "Nacional",
    unidad: "Porcentaje",
    tipoCalculo: "numerador",
    numerador: "Mujeres en edad fértil que usan métodos modernos",
    denominador: "Total de mujeres en edad fértil",
    formula: "",
    sentido: "Subir",
    tipoFuente: "Encuesta",
    fuenteDatos: "Encuesta Demográfica y de Salud Familiar (ENDES) – INEI",
    limitacion: "Inferencia departamental",
    supuestos: "Se mantiene el módulo de la encuesta",
    precisiones: "Mujeres de 15 a 49 años",
    periodicidad: "Anual",
    programacion: "SI",
    gestion: "SI",
    evaluacion: "SI",
    anioInicio: "2026",
    anioFin: "",
    estado: "SI",
    fechaDesde: "23/01/2026",
    fechaHasta: "",
    desagregaciones: [{ ambito: "8 CUSCO", area: "2 URBANO", periodicidad: "Anual" }, { ambito: "8 CUSCO", area: "3 RURAL", periodicidad: "Anual" }, { ambito: "15 LIMA", area: "1 TOTAL", periodicidad: "Anual" }],
    variables: [{ variable: "usa_metodo_moderno", descripcion: "Mujer en edad fértil que usa un método moderno de planificación familiar", fuente: "ENDES – INEI, base de datos anual", tipoVariable: "Categórica dicotómica (1 = sí, 0 = no)" }, { variable: "mujeres_edad_fertil", descripcion: "Mujeres de 15 a 49 años entrevistadas", fuente: "ENDES – INEI, base de datos anual", tipoVariable: "Numérica discreta (conteo)" }, { variable: "factor_expansion", descripcion: "Factor de expansión anual de la persona, para obtener estimaciones poblacionales", fuente: "ENDES – INEI, base de datos anual", tipoVariable: "Numérica continua (ponderador)" }],
    validaciones: [{ elemento: "Rango de edad de la población", descripcion: "Solo mujeres de 15 a 49 años" }, { elemento: "Ponderación con factor de expansión", descripcion: "Las estimaciones se calculan aplicando el factor de expansión anual de la encuesta" }, { elemento: "Control de rango del resultado", descripcion: "El valor calculado debe estar entre 0 y 100; si no, se revisan numerador y denominador" }],
  },
  {
    codigo: "9013",
    pp: "0002",
    nombre: "Porcentaje de población informada sobre métodos de planificación familiar",
    dimension: "eficacia",
    nivelMedicion: "2. Producto",
    productoCodigo: "3033258",
    alcance: "Nacional",
    nivelResponsable: "Nacional",
    unidad: "Porcentaje",
    tipoCalculo: "numerador",
    numerador: "Personas informadas",
    denominador: "Población objetivo",
    formula: "",
    sentido: "Subir",
    tipoFuente: "Encuesta",
    fuenteDatos: "Encuesta Demográfica y de Salud Familiar (ENDES) – INEI",
    limitacion: "Inferencia solo nacional",
    supuestos: "Se mantiene el módulo de la encuesta",
    precisiones: "Información recibida en los últimos 12 meses",
    periodicidad: "Anual",
    programacion: "SI",
    gestion: "SI",
    evaluacion: "SI",
    anioInicio: "2024",
    anioFin: "2025",
    estado: "NO",
    fechaDesde: "15/01/2024",
    fechaHasta: "31/12/2025",
    desagregaciones: [],
    variables: [{ variable: "informada_planificacion", descripcion: "Persona que recibió información sobre métodos de planificación familiar en los últimos 12 meses", fuente: "ENDES – INEI, base de datos anual", tipoVariable: "Categórica dicotómica (1 = sí, 0 = no)" }, { variable: "poblacion_objetivo_informacion", descripcion: "Población objetivo de las acciones de información", fuente: "ENDES – INEI, base de datos anual", tipoVariable: "Numérica discreta (conteo)" }, { variable: "factor_expansion", descripcion: "Factor de expansión anual de la persona, para obtener estimaciones poblacionales", fuente: "ENDES – INEI, base de datos anual", tipoVariable: "Numérica continua (ponderador)" }],
    validaciones: [{ elemento: "Periodo de referencia de la información", descripcion: "Información recibida en los últimos 12 meses" }, { elemento: "Ponderación con factor de expansión", descripcion: "Las estimaciones se calculan aplicando el factor de expansión anual de la encuesta" }, { elemento: "Control de rango del resultado", descripcion: "El valor calculado debe estar entre 0 y 100; si no, se revisan numerador y denominador" }],
  },
];
